---
- name: jekyll_site | Dependencies | Install additional packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - build-essential
    - zlib1g-dev
    - git
    - nmap
  become: yes